/* Generated By:JavaCC: Do not edit this line. DSL_LARATreeConstants.java Version 5.0 */
package pack;

public interface DSL_LARATreeConstants
{
  public int JJTSTART = 0;
  public int JJTRULE = 1;
  public int JJTUSE = 2;
  public int JJTVOID = 3;
  public int JJTIFSTATEMENT = 4;
  public int JJTLEFT = 5;
  public int JJTRIGHT = 6;
  public int JJTLEFTOP = 7;
  public int JJTRIGHTOP = 8;
  public int JJTCONDITION = 9;
  public int JJTBODY = 10;
  public int JJTTYPEDEF = 11;
  public int JJTDATATYPECONVRULES = 12;
  public int JJTCOMUTATIVE = 13;
  public int JJTLHS = 14;
  public int JJTIDENT = 15;
  public int JJTARGS = 16;
  public int JJTIR = 17;
  public int JJTTYPE = 18;
  public int JJTBRACKETS = 19;
  public int JJTSQUAREBRACKETS = 20;
  public int JJTTEMPVARS = 21;
  public int JJTRULES = 22;
  public int JJTFOREACHSTATEMENT = 23;
  public int JJTKEY = 24;
  public int JJTTAG = 25;
  public int JJTVAR = 26;
  public int JJTELEM = 27;
  public int JJTITER = 28;
  public int JJTPROGRAM = 29;
  public int JJTFUNCTION = 30;
  public int JJTEQUALS = 31;
  public int JJTCOLONS = 32;
  public int JJTLIST = 33;
  public int JJTITERLIST = 34;
  public int JJTINSERT = 35;
  public int JJTBEFORE = 36;
  public int JJTAFTER = 37;
  public int JJTAROUND = 38;
  public int JJTEND = 39;
  public int JJTBEGIN = 40;
  public int JJTRHS = 41;
  public int JJTSET = 42;
  public int JJTSETFIXED = 43;
  public int JJTWITHSTATEMENT = 44;
  public int JJTMODULE = 45;
  public int JJTDO = 46;
  public int JJTCALL = 47;
  public int JJTOPERATION = 48;
  public int JJTCONFIG = 49;
  public int JJTSTATEMENT = 50;
  public int JJTTARGETCODE = 51;
  public int JJTFPRINTF = 52;
  public int JJTNUMBER = 53;
  public int JJTOP = 54;
  public int JJTASSIGNMENT = 55;
  public int JJTMETHOD = 56;
  public int JJTSCREEN = 57;
  public int JJTFILEID = 58;
  public int JJTQUOTED = 59;
  public int JJTFILE = 60;
  public int JJTPRINT = 61;
  public int JJTWARNING = 62;
  public int JJTARG = 63;
  public int JJTPARAM = 64;
  public int JJTIDENTIFIER = 65;
  public int JJTINT8 = 66;
  public int JJTINT16 = 67;
  public int JJTINT32 = 68;
  public int JJTUINT8 = 69;
  public int JJTUINT16 = 70;
  public int JJTUINT32 = 71;
  public int JJTCHAR = 72;
  public int JJTBOOL = 73;
  public int JJTDOUBLE = 74;
  public int JJTSINGLE = 75;
  public int JJTFLOAT = 76;
  public int JJTINT = 77;
  public int JJTIF = 78;
  public int JJTELSE = 79;
  public int JJTOR = 80;
  public int JJTAND = 81;
  public int JJTXOR = 82;
  public int JJTMUL = 83;
  public int JJTSUM = 84;
  public int JJTSUB = 85;
  public int JJTOVERFLOW = 86;
  public int JJTROUND = 87;
  public int JJTWRAP = 88;
  public int JJTFLOOR = 89;
  public int JJTDEPENDENTSTMT = 90;
  public int JJTOPSCONFIGRULES = 91;
  public int JJTDECOMPOSE = 92;
  public int JJTFIXED = 93;
  public int JJTMAX = 94;
  public int JJTMIN = 95;


  public String[] jjtNodeName = {
    "Start",
    "Rule",
    "Use",
    "void",
    "IfStatement",
    "Left",
    "Right",
    "LeftOp",
    "RightOp",
    "Condition",
    "Body",
    "TypeDef",
    "DataTypeConvRules",
    "Comutative",
    "Lhs",
    "Ident",
    "Args",
    "Ir",
    "Type",
    "Brackets",
    "SquareBrackets",
    "TempVars",
    "Rules",
    "ForEachStatement",
    "Key",
    "Tag",
    "Var",
    "Elem",
    "Iter",
    "Program",
    "Function",
    "Equals",
    "Colons",
    "List",
    "IterList",
    "Insert",
    "Before",
    "After",
    "Around",
    "End",
    "Begin",
    "Rhs",
    "Set",
    "SetFixed",
    "WithStatement",
    "Module",
    "Do",
    "Call",
    "Operation",
    "Config",
    "Statement",
    "Targetcode",
    "Fprintf",
    "Number",
    "Op",
    "Assignment",
    "Method",
    "Screen",
    "FileId",
    "Quoted",
    "File",
    "Print",
    "Warning",
    "Arg",
    "Param",
    "Identifier",
    "Int8",
    "Int16",
    "Int32",
    "UInt8",
    "UInt16",
    "UInt32",
    "Char",
    "Bool",
    "Double",
    "Single",
    "Float",
    "Int",
    "If",
    "Else",
    "Or",
    "And",
    "Xor",
    "Mul",
    "Sum",
    "Sub",
    "Overflow",
    "Round",
    "Wrap",
    "Floor",
    "DependentStmt",
    "OpsConfigRules",
    "Decompose",
    "Fixed",
    "Max",
    "Min",
  };
}
/* JavaCC - OriginalChecksum=c4b3d92c3996f927ee6e2f7d7172a317 (do not edit this line) */
